import { StyleSheet } from 'react-native';

import { theme } from '@/lib/theme';

export const FOCUS_CARD_HEIGHT = 278;

export const balanceOverviewStyles = StyleSheet.create({
  supportText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.body,
    lineHeight: 22,
  },
  loadingText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.body,
    lineHeight: 22,
    textAlign: 'center',
  },
  detailFilters: {
    gap: theme.spacing.sm,
  },
  detailCard: {
    gap: theme.spacing.sm,
  },
  detailHeroAmount: {
    color: theme.colors.text,
    fontSize: 34,
    fontWeight: '800',
    letterSpacing: -0.8,
    lineHeight: 40,
  },
  detailInsight: {
    color: theme.colors.text,
    fontSize: theme.typography.callout,
    fontWeight: '700',
    lineHeight: 22,
  },
  detailGrid: {
    gap: theme.spacing.sm,
  },
  detailGridCard: {
    gap: theme.spacing.xs,
  },
  detailMetricAmount: {
    color: theme.colors.text,
    fontSize: theme.typography.title2,
    fontWeight: '800',
    lineHeight: 28,
  },
  projectionSummary: {
    gap: theme.spacing.sm,
  },
  rankingRow: {
    alignItems: 'center',
    borderBottomColor: theme.colors.hairline,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: theme.spacing.sm,
    paddingVertical: theme.spacing.md,
  },
  rankingIcon: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceMuted,
    borderRadius: theme.radius.large,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  rankingCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  detailRowTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.callout,
    fontWeight: '800',
    lineHeight: 20,
  },
  detailRowDescription: {
    color: theme.colors.text,
    fontSize: theme.typography.footnote,
    lineHeight: 18,
  },
  detailRowAmount: {
    color: theme.colors.text,
    fontSize: theme.typography.callout,
    fontWeight: '800',
    lineHeight: 20,
    maxWidth: 118,
    textAlign: 'right',
  },
  carouselDots: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: theme.spacing.xs,
    justifyContent: 'center',
    marginTop: -theme.spacing.xs,
  },
  carouselDotHitArea: {
    alignItems: 'center',
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  carouselDot: {
    backgroundColor: theme.colors.border,
    borderRadius: theme.radius.pill,
    height: 7,
    width: 7,
  },
  carouselDotSelected: {
    backgroundColor: theme.colors.primary,
    width: 18,
  },
  carouselViewport: {
    overflow: 'hidden',
  },
  carousel: {
    marginHorizontal: -theme.spacing.xs,
  },
  carouselPage: {
    paddingHorizontal: theme.spacing.xs,
  },
  focusCard: {
    backgroundColor: theme.colors.background,
    borderColor: theme.colors.hairline,
    gap: theme.spacing.sm,
    height: FOCUS_CARD_HEIGHT,
  },
  balanceFocusCard: {
    gap: theme.spacing.sm,
  },
  balanceHomeBody: {
    alignItems: 'center',
    flex: 1,
    gap: theme.spacing.sm,
    justifyContent: 'center',
    width: '100%',
  },
  homeBalanceAmount: {
    color: theme.colors.text,
    fontSize: 44,
    fontWeight: '800',
    lineHeight: 52,
    marginTop: theme.spacing.xs,
    textAlign: 'center',
  },
  homeBalanceMetricsRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: theme.spacing.xl,
    justifyContent: 'center',
    marginTop: theme.spacing.xs,
    width: '100%',
  },
  balanceMetricItem: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 4,
    justifyContent: 'center',
    maxWidth: 190,
    minWidth: 0,
  },
  balanceMetricLabel: {
    fontSize: theme.typography.footnote,
    fontWeight: '800',
    lineHeight: 17,
  },
  balanceMetricAmount: {
    flexShrink: 1,
    fontSize: theme.typography.callout,
    fontWeight: '800',
    lineHeight: 19,
  },
  cardEyebrow: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption,
    fontWeight: '800',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  focusCardHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: theme.spacing.sm,
    justifyContent: 'space-between',
    minHeight: 30,
  },
  focusCardTitle: {
    flex: 1,
    color: theme.colors.text,
    fontSize: theme.typography.title3,
    fontWeight: '800',
    lineHeight: 24,
    minWidth: 0,
  },
  focusCardContextPill: {
    borderColor: theme.colors.hairline,
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  focusCardContextText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption,
    fontWeight: '800',
    lineHeight: 15,
  },
  cardMeta: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption,
    lineHeight: 17,
  },
  heroAmount: {
    color: theme.colors.text,
    fontSize: 38,
    fontWeight: '800',
    letterSpacing: -1,
    lineHeight: 44,
  },
  focusAmount: {
    color: theme.colors.text,
    fontSize: 32,
    fontWeight: '800',
    letterSpacing: -0.8,
    lineHeight: 38,
  },
  focusTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.title2,
    fontWeight: '800',
    letterSpacing: -0.3,
    lineHeight: 28,
  },
  focusCaption: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.footnote,
    lineHeight: 18,
  },
  trendChip: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'transparent',
    borderColor: theme.colors.hairline,
    borderWidth: 1,
    borderRadius: theme.radius.medium,
    flexDirection: 'row',
    gap: theme.spacing.xs,
    maxWidth: '100%',
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.xs,
  },
  trendChipCentered: {
    alignSelf: 'center',
  },
  trendChipPositive: {
    borderColor: theme.colors.success,
  },
  trendChipNegative: {
    borderColor: theme.colors.warning,
  },
  trendChipValue: {
    color: theme.colors.text,
    flexShrink: 1,
    fontSize: theme.typography.footnote,
    fontWeight: '800',
    lineHeight: 17,
  },
  trendChipContext: {
    color: theme.colors.textMuted,
    flexShrink: 1,
    fontSize: theme.typography.caption,
    fontWeight: '700',
    lineHeight: 15,
  },
  emptyCardState: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderColor: theme.colors.hairline,
    borderWidth: 1,
    borderRadius: theme.radius.medium,
    flexDirection: 'row',
    gap: theme.spacing.xs,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
  },
  emptyCardText: {
    color: theme.colors.textMuted,
    flex: 1,
    fontSize: theme.typography.footnote,
    fontWeight: '700',
    lineHeight: 18,
  },
  barList: {
    gap: theme.spacing.sm,
  },
  barRow: {
    gap: theme.spacing.xs,
  },
  barRowHeader: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    gap: theme.spacing.sm,
    justifyContent: 'space-between',
  },
  barCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  barMetaLine: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: theme.spacing.xs,
    minWidth: 0,
  },
  barMetaText: {
    flex: 1,
    minWidth: 0,
  },
  barLabel: {
    color: theme.colors.text,
    fontSize: theme.typography.callout,
    fontWeight: '800',
    lineHeight: 20,
  },
  barAmount: {
    color: theme.colors.text,
    fontSize: theme.typography.callout,
    fontWeight: '800',
    lineHeight: 20,
    maxWidth: 112,
    textAlign: 'right',
  },
  barTrack: {
    backgroundColor: theme.colors.surfaceMuted,
    borderRadius: theme.radius.pill,
    height: 8,
    overflow: 'hidden',
  },
  barFill: {
    borderRadius: theme.radius.pill,
    height: '100%',
  },
  barFillPositive: {
    backgroundColor: theme.colors.success,
  },
  barFillNegative: {
    backgroundColor: theme.colors.warning,
  },
  barFillNeutral: {
    backgroundColor: theme.colors.primary,
  },
  miniTrend: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderColor: theme.colors.hairline,
    borderWidth: 1,
    borderRadius: theme.radius.pill,
    flexDirection: 'row',
    gap: 2,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  miniTrendPositive: {
    borderColor: theme.colors.success,
  },
  miniTrendNegative: {
    borderColor: theme.colors.warning,
  },
  miniTrendText: {
    color: theme.colors.textMuted,
    fontSize: 10,
    fontWeight: '800',
    lineHeight: 12,
  },
  compactMetricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing.sm,
  },
  compactMetricTile: {
    alignItems: 'flex-start',
    backgroundColor: 'transparent',
    borderColor: theme.colors.hairline,
    borderWidth: 1,
    borderRadius: theme.radius.medium,
    flexBasis: '30%',
    flexGrow: 1,
    gap: 2,
    minWidth: 92,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.sm,
  },
  compactMetricValue: {
    color: theme.colors.text,
    fontSize: theme.typography.title3,
    fontWeight: '800',
    lineHeight: 23,
  },
  compactMetricLabel: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption,
    fontWeight: '700',
    lineHeight: 15,
  },
  inlineMetric: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceMuted,
    borderRadius: theme.radius.medium,
    flexDirection: 'row',
    gap: theme.spacing.sm,
    justifyContent: 'space-between',
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
  },
  inlineMetricValue: {
    color: theme.colors.text,
    fontSize: theme.typography.title3,
    fontWeight: '800',
    minWidth: 52,
  },
  inlineMetricLabel: {
    color: theme.colors.textMuted,
    flex: 1,
    fontSize: theme.typography.footnote,
    fontWeight: '700',
    lineHeight: 18,
    textAlign: 'right',
  },
  positiveText: {
    color: theme.colors.success,
  },
  negativeText: {
    color: theme.colors.warning,
  },
  pressed: {
    opacity: 0.9,
  },
});
