import { StyleSheet } from 'react-native';

import { theme } from '@/lib/theme';

export const FOCUS_CARD_HEIGHT = 304;

export const balanceOverviewStyles = StyleSheet.create({
  supportText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.body,
    lineHeight: 22,
  },
  loadingText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.body,
    lineHeight: 22,
    textAlign: 'center',
  },
  detailFilters: {
    gap: theme.spacing.sm,
  },
  detailCard: {
    gap: theme.spacing.sm,
  },
  detailHeroAmount: {
    color: theme.colors.text,
    fontSize: 34,
    fontWeight: '800',
    letterSpacing: -0.8,
    lineHeight: 40,
  },
  detailInsight: {
    color: theme.colors.text,
    fontSize: theme.typography.callout,
    fontWeight: '700',
    lineHeight: 22,
  },
  detailGrid: {
    gap: theme.spacing.sm,
  },
  detailGridCard: {
    gap: theme.spacing.xs,
  },
  detailMetricAmount: {
    color: theme.colors.text,
    fontSize: theme.typography.title2,
    fontWeight: '800',
    lineHeight: 28,
  },
  rankingRow: {
    alignItems: 'center',
    borderBottomColor: theme.colors.hairline,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: theme.spacing.sm,
    paddingVertical: theme.spacing.md,
  },
  rankingIcon: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceMuted,
    borderRadius: theme.radius.large,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  rankingCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  detailRowTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.callout,
    fontWeight: '800',
    lineHeight: 20,
  },
  detailRowDescription: {
    color: theme.colors.text,
    fontSize: theme.typography.footnote,
    lineHeight: 18,
  },
  detailRowAmount: {
    color: theme.colors.text,
    fontSize: theme.typography.callout,
    fontWeight: '800',
    lineHeight: 20,
    maxWidth: 118,
    textAlign: 'right',
  },
  carouselDots: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: theme.spacing.xs,
    justifyContent: 'center',
    marginTop: -4,
  },
  carouselBlock: {
    gap: theme.spacing.xs,
    paddingHorizontal: theme.spacing.xs,
  },
  carouselDotHitArea: {
    alignItems: 'center',
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  carouselDot: {
    backgroundColor: theme.colors.primaryGhost,
    borderRadius: theme.radius.pill,
    height: 7,
    width: 7,
  },
  carouselDotSelected: {
    backgroundColor: theme.colors.brandGreen,
    width: 18,
  },
  carouselViewport: {
    height: FOCUS_CARD_HEIGHT,
    overflow: 'hidden',
  },
  focusCard: {
    backgroundColor: 'transparent',
    gap: theme.spacing.sm,
    height: FOCUS_CARD_HEIGHT,
    overflow: 'hidden',
  },
  balanceFocusCard: {
    backgroundColor: 'transparent',
    gap: theme.spacing.sm,
  },
  balanceFocusHeaderRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: theme.spacing.xs,
    minHeight: 48,
  },
  balanceFocusTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  balanceFocusHappyFacesCounter: {
    flexShrink: 0,
    height: 42,
    minWidth: 80,
    paddingHorizontal: 10,
  },
  visualFocusCard: {
    backgroundColor: 'transparent',
  },
  circleStageCard: {
    gap: 0,
  },
  categoryFocusCard: {
    gap: 0,
  },
  categoryUniverse: {
    flex: 1,
    minHeight: 0,
    position: 'relative',
  },
  categoryFixedHeader: {
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 2,
  },
  categoryUniverseEmptyState: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: theme.spacing.md,
  },
  peopleRankingScene: {
    flex: 1,
    minHeight: 0,
    position: 'relative',
  },
  peopleRankingGuide: {
    backgroundColor: theme.colors.hairline,
    borderRadius: theme.radius.pill,
    height: 2,
    left: 70,
    opacity: 0.8,
    position: 'absolute',
    top: 82,
    transform: [{ rotate: '28deg' }],
    width: 162,
  },
  peopleRankItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 5,
    position: 'absolute',
  },
  peopleRankOne: {
    left: 4,
    top: 2,
  },
  peopleRankTwo: {
    right: 6,
    top: 28,
  },
  peopleRankThree: {
    left: 34,
    top: 78,
  },
  peopleRankFour: {
    right: 22,
    top: 116,
  },
  peopleRankFive: {
    bottom: 0,
    left: 4,
  },
  peopleRankNumber: {
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    height: 20,
    justifyContent: 'center',
    width: 20,
  },
  peopleRankNumberText: {
    fontSize: 10,
    fontWeight: '900',
    lineHeight: 12,
  },
  peopleRankAvatarRing: {
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.pill,
    borderWidth: 2,
    justifyContent: 'center',
    padding: 2,
    ...theme.shadow.card,
  },
  peopleRankCopy: {
    gap: 2,
    minWidth: 62,
  },
  peopleRankValuePill: {
    alignItems: 'center',
    borderRadius: theme.radius.pill,
    minWidth: 58,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  peopleRankValue: {
    fontSize: theme.typography.caption,
    fontWeight: '900',
    lineHeight: 15,
  },
  peopleRankName: {
    color: theme.colors.textMuted,
    fontSize: 10,
    fontWeight: '800',
    lineHeight: 12,
    maxWidth: 64,
  },
  categoryProgressFrame: {
    flex: 1,
    overflow: 'hidden',
    paddingVertical: 0,
  },
  categoryProgressField: {
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
    position: 'relative',
  },
  categoryParticle: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
  },
  categoryProgressPressable: {
    alignItems: 'center',
    borderRadius: theme.radius.pill,
    justifyContent: 'center',
    padding: 1,
  },
  categoryProgressBubble: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryProgressIconWrap: {
    alignItems: 'center',
    height: 58,
    justifyContent: 'center',
    position: 'relative',
    width: 58,
  },
  categoryProgressSvg: {
    position: 'absolute',
  },
  categoryProgressIcon: {
    alignItems: 'center',
    borderRadius: theme.radius.pill,
    gap: 1,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  categoryProgressInnerValue: {
    fontSize: 10,
    fontWeight: '900',
    lineHeight: 11,
    maxWidth: 48,
    textAlign: 'center',
  },
  simplifyScene: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    minHeight: 0,
    position: 'relative',
  },
  simplifySvg: {
    position: 'absolute',
  },
  simplifyFlowDot: {
    backgroundColor: theme.colors.brandGreen,
    borderColor: theme.colors.surface,
    borderRadius: theme.radius.pill,
    borderWidth: 2,
    height: 16,
    position: 'absolute',
    top: 80,
    width: 16,
  },
  simplifyScoreBubble: {
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.success,
    borderRadius: theme.radius.pill,
    borderWidth: 2,
    height: 92,
    justifyContent: 'center',
    width: 92,
    ...theme.shadow.card,
  },
  simplifyScoreValue: {
    color: theme.colors.text,
    fontSize: 34,
    fontWeight: '900',
    lineHeight: 38,
  },
  simplifyScoreLabel: {
    color: theme.colors.textMuted,
    fontSize: 10,
    fontWeight: '900',
    lineHeight: 12,
    textTransform: 'uppercase',
  },
  simplifyResolvedAmount: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.hairline,
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    bottom: 0,
    color: theme.colors.text,
    fontSize: theme.typography.caption,
    fontWeight: '900',
    lineHeight: 15,
    paddingHorizontal: 10,
    paddingVertical: 4,
    position: 'absolute',
  },
  visualMetricRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: theme.spacing.sm,
    justifyContent: 'center',
  },
  visualMetricBubble: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.hairline,
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 5,
    minWidth: 54,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  visualMetricValue: {
    color: theme.colors.text,
    fontSize: theme.typography.caption,
    fontWeight: '900',
    lineHeight: 15,
  },
  circleStageScene: {
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
    position: 'relative',
    width: '100%',
  },
  circleStageGraph: {
    alignItems: 'center',
    height: 224,
    justifyContent: 'center',
    left: '50%',
    marginLeft: -112,
    position: 'absolute',
    top: 52,
    width: 224,
    zIndex: 2,
  },
  circleStageTitleDock: {
    left: theme.spacing.lg,
    position: 'absolute',
    right: theme.spacing.lg,
    top: theme.spacing.lg,
    zIndex: 5,
  },
  circleStageIdleGraph: {
    opacity: 0.5,
  },
  circleStageRing: {
    marginRight: 0,
  },
  circleStageCalloutDock: {
    alignItems: 'center',
    position: 'absolute',
    right: theme.spacing.md,
    top: theme.spacing.md,
    zIndex: 4,
  },
  circleStageCallout: {
    alignItems: 'center',
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    minHeight: 30,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: 5,
  },
  circleStageCalloutDot: {
    borderRadius: theme.radius.pill,
    height: 7,
    width: 7,
  },
  circleStageCalloutText: {
    color: theme.colors.text,
    fontSize: theme.typography.caption,
    fontWeight: '900',
    lineHeight: 15,
  },
  balanceHomeBody: {
    alignItems: 'stretch',
    flex: 1,
    gap: theme.spacing.md,
    justifyContent: 'space-between',
    width: '100%',
  },
  homeBalanceHero: {
    alignItems: 'center',
    flex: 1,
    gap: theme.spacing.xs,
    justifyContent: 'center',
    minHeight: 0,
  },
  homeBalanceAmount: {
    color: theme.colors.text,
    fontSize: 44,
    fontWeight: '900',
    lineHeight: 50,
    textAlign: 'center',
  },
  homeBalanceMetricsRow: {
    alignItems: 'stretch',
    flexDirection: 'row',
    gap: theme.spacing.sm,
    justifyContent: 'center',
    width: '100%',
  },
  balanceMetricItem: {
    alignItems: 'center',
    backgroundColor: theme.glass.background,
    borderColor: theme.colors.hairline,
    borderRadius: theme.radius.medium,
    borderWidth: 1,
    flex: 1,
    gap: 3,
    justifyContent: 'center',
    minWidth: 0,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: 10,
  },
  balanceMetricLabelRow: {
    alignItems: 'center',
    alignSelf: 'stretch',
    flexDirection: 'row',
    gap: 5,
    justifyContent: 'center',
    minWidth: 0,
  },
  balanceMetricLabel: {
    flexShrink: 1,
    fontSize: theme.typography.footnote,
    fontWeight: '800',
    lineHeight: 17,
  },
  balanceMetricAmount: {
    alignSelf: 'stretch',
    fontSize: theme.typography.callout,
    fontWeight: '900',
    lineHeight: 19,
    maxWidth: '100%',
    textAlign: 'center',
  },
  cardEyebrow: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption,
    fontWeight: '800',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  focusCardHeader: {
    alignItems: 'center',
  },
  focusCardHeaderStart: {
    alignItems: 'flex-start',
  },
  focusCardTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.title3,
    fontWeight: '800',
    lineHeight: 24,
    minWidth: 0,
    textAlign: 'center',
  },
  focusCardTitleStart: {
    textAlign: 'left',
  },
  cardMeta: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption,
    lineHeight: 17,
  },
  heroAmount: {
    color: theme.colors.text,
    fontSize: 38,
    fontWeight: '800',
    letterSpacing: -1,
    lineHeight: 44,
  },
  focusAmount: {
    color: theme.colors.text,
    fontSize: 32,
    fontWeight: '800',
    letterSpacing: -0.8,
    lineHeight: 38,
  },
  focusTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.title2,
    fontWeight: '800',
    letterSpacing: -0.3,
    lineHeight: 28,
  },
  focusCaption: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.footnote,
    lineHeight: 18,
  },
  trendChip: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: theme.glass.accentBackground,
    borderColor: theme.colors.hairline,
    borderWidth: 1,
    borderRadius: theme.radius.pill,
    flexDirection: 'row',
    gap: theme.spacing.xs,
    maxWidth: '100%',
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.xs,
  },
  trendChipCentered: {
    alignSelf: 'center',
  },
  trendChipPositive: {
    borderColor: theme.colors.success,
  },
  trendChipNegative: {
    borderColor: theme.colors.warning,
  },
  trendChipValue: {
    color: theme.colors.text,
    flexShrink: 1,
    fontSize: theme.typography.footnote,
    fontWeight: '800',
    lineHeight: 17,
  },
  trendChipContext: {
    color: theme.colors.textMuted,
    flexShrink: 1,
    fontSize: theme.typography.caption,
    fontWeight: '700',
    lineHeight: 15,
  },
  emptyCardState: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderColor: theme.colors.hairline,
    borderWidth: 1,
    borderRadius: theme.radius.medium,
    flexDirection: 'row',
    gap: theme.spacing.xs,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
  },
  emptyCardText: {
    color: theme.colors.textMuted,
    flex: 1,
    fontSize: theme.typography.footnote,
    fontWeight: '700',
    lineHeight: 18,
  },
  positiveText: {
    color: theme.colors.success,
  },
  negativeText: {
    color: theme.colors.warning,
  },
  pressed: {
    opacity: 0.9,
  },
});
