import { StyleSheet } from 'react-native';

import { theme } from '@/lib/theme';

export const addPersonContactsSheetStyles = StyleSheet.create({
  sheetScrim: {
    backgroundColor: theme.colors.overlay,
    flex: 1,
    justifyContent: 'flex-end',
  },
  sheetBackdrop: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  sheet: {
    backgroundColor: theme.colors.surface,
    borderTopLeftRadius: theme.radius.large,
    borderTopRightRadius: theme.radius.large,
    gap: theme.spacing.md,
    maxHeight: '88%',
    paddingBottom: theme.spacing.lg,
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.md,
  },
  sheetHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: theme.spacing.sm,
    justifyContent: 'space-between',
  },
  sheetTitle: {
    color: theme.colors.text,
    flex: 1,
    fontSize: theme.typography.body,
    fontWeight: '800',
  },
  closeButton: {
    alignItems: 'center',
    borderRadius: theme.radius.pill,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  inPersonBlock: {
    backgroundColor: theme.colors.primarySoft,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.medium,
    borderWidth: 1,
    gap: theme.spacing.sm,
    padding: theme.spacing.sm,
  },
  inPersonCollapseSlot: {
    overflow: 'hidden',
  },
  contactControlsStack: {
    minWidth: 0,
  },
  inPersonCopy: {
    gap: 2,
  },
  inPersonTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.callout,
    fontWeight: '800',
  },
  inPersonText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption,
    lineHeight: 16,
  },
  inPersonActions: {
    flexDirection: 'row',
    gap: theme.spacing.sm,
  },
  contextBlock: {
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.large,
    borderWidth: 1,
    gap: 4,
    marginTop: theme.spacing.md,
    padding: theme.spacing.md,
  },
  contextLabel: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption,
    fontWeight: '700',
  },
  contextBody: {
    color: theme.colors.text,
    fontSize: theme.typography.callout,
    lineHeight: 20,
  },
  qrActionButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: theme.spacing.sm,
  },
  qrActionButtonPrimary: {
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
  },
  qrActionText: {
    color: theme.colors.text,
    fontSize: theme.typography.caption,
    fontWeight: '800',
  },
  qrActionTextPrimary: {
    color: theme.colors.white,
  },
  qrActionLabelClip: {
    overflow: 'hidden',
  },
  searchWrap: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.medium,
    borderWidth: 1,
    flexDirection: 'row',
    gap: theme.spacing.xs,
    minHeight: 52,
    paddingHorizontal: theme.spacing.sm,
  },
  searchStickyWrap: {
    backgroundColor: theme.colors.surface,
    paddingVertical: 1,
    zIndex: 2,
  },
  searchWrapSpaced: {
    marginTop: theme.spacing.md,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 0,
  },
  compactQrActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: theme.spacing.xs,
    overflow: 'hidden',
  },
  compactQrButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  compactQrButtonPrimary: {
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
  },
  sheetContent: {
    gap: theme.spacing.md,
    paddingBottom: theme.spacing.xl,
  },
  contactSection: {
    gap: theme.spacing.sm,
  },
  sectionLabel: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption,
    fontWeight: '800',
  },
  contactList: {
    gap: theme.spacing.sm,
  },
  contactRow: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceMuted,
    borderRadius: theme.radius.small,
    flexDirection: 'row',
    gap: theme.spacing.sm,
    minHeight: 72,
    padding: theme.spacing.sm,
  },
  contactRowInApp: {
    backgroundColor: theme.colors.successSoft,
    borderColor: theme.colors.successSoft,
    borderWidth: 1,
  },
  contactCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  contactName: {
    color: theme.colors.text,
    fontSize: theme.typography.callout,
    fontWeight: '700',
  },
  contactPhone: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption,
    lineHeight: 16,
  },
  contactActionButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.primary,
    borderRadius: theme.radius.pill,
    flexDirection: 'row',
    gap: 5,
    justifyContent: 'center',
    minHeight: 34,
    minWidth: 84,
    paddingHorizontal: theme.spacing.sm,
  },
  contactActionInvite: {
    backgroundColor: theme.colors.warning,
  },
  contactActionMuted: {
    backgroundColor: theme.colors.muted,
  },
  contactActionText: {
    color: theme.colors.white,
    fontSize: theme.typography.caption,
    fontWeight: '800',
  },
  pressed: {
    opacity: 0.7,
  },
  disabled: {
    opacity: 0.52,
  },
  helperText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.footnote,
    lineHeight: 18,
  },
  emptyState: {
    alignItems: 'center',
    gap: theme.spacing.xs,
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.xl,
  },
  permissionBox: {
    backgroundColor: theme.colors.surfaceMuted,
    borderRadius: theme.radius.small,
    gap: theme.spacing.sm,
    padding: theme.spacing.md,
  },
  emptyTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.callout,
    fontWeight: '800',
  },
  emptyText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.footnote,
    lineHeight: 18,
  },
  manualInviteCard: {
    alignSelf: 'stretch',
    borderRadius: theme.radius.small,
    borderWidth: 1,
    gap: theme.spacing.sm,
    marginTop: theme.spacing.sm,
    padding: theme.spacing.sm,
  },
  manualInviteCopy: {
    gap: 2,
  },
  manualInviteTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.callout,
    fontWeight: '800',
  },
  scannerWrap: {
    borderRadius: theme.radius.medium,
    overflow: 'hidden',
  },
  scanner: {
    height: 260,
    width: '100%',
  },
  optionScrim: {
    alignItems: 'center',
    backgroundColor: theme.colors.overlay,
    flex: 1,
    justifyContent: 'center',
    padding: theme.spacing.lg,
  },
  optionInlineScrim: {
    ...StyleSheet.absoluteFillObject,
    elevation: 20,
    zIndex: 20,
  },
  floatingOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    backgroundColor: theme.colors.overlay,
    elevation: 10,
    justifyContent: 'center',
    padding: theme.spacing.lg,
    zIndex: 10,
  },
  scannerCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.large,
    gap: theme.spacing.md,
    maxWidth: 430,
    padding: theme.spacing.md,
    width: '100%',
  },
  modalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: theme.spacing.sm,
    justifyContent: 'space-between',
  },
  modalHeaderCopy: {
    flex: 1,
    gap: 3,
  },
  myQrCard: {
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.large,
    gap: theme.spacing.md,
    maxWidth: 380,
    padding: theme.spacing.lg,
    width: '100%',
  },
  qrProfile: {
    alignItems: 'center',
    alignSelf: 'stretch',
    flexDirection: 'row',
    gap: theme.spacing.sm,
  },
  qrCodeShell: {
    alignItems: 'center',
    backgroundColor: theme.colors.white,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.large,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 238,
    padding: theme.spacing.md,
    width: '100%',
  },
  qrLoading: {
    alignItems: 'center',
    gap: theme.spacing.sm,
    justifyContent: 'center',
    minHeight: 210,
  },
  qrModalActions: {
    alignSelf: 'stretch',
    gap: theme.spacing.sm,
  },
  optionCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.large,
    gap: theme.spacing.md,
    maxWidth: 430,
    padding: theme.spacing.lg,
    width: '100%',
  },
  optionTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.title3,
    fontWeight: '800',
  },
  optionList: {
    gap: theme.spacing.sm,
  },
  optionNotice: {
    alignItems: 'center',
    backgroundColor: theme.colors.primarySoft,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.small,
    borderWidth: 1,
    flexDirection: 'row',
    gap: theme.spacing.xs,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.xs,
  },
  optionNoticeText: {
    color: theme.colors.text,
    flex: 1,
    fontSize: theme.typography.caption,
    fontWeight: '700',
    lineHeight: 16,
  },
  optionRow: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceMuted,
    borderRadius: theme.radius.small,
    flexDirection: 'row',
    gap: theme.spacing.sm,
    padding: theme.spacing.sm,
  },
});
