import { StyleSheet } from 'react-native';

import { theme } from '@/lib/theme';

export const categoriesIndexScreenStyles = StyleSheet.create({
  loadingState: { alignItems: 'center', gap: theme.spacing.sm },
  supportText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.callout,
    lineHeight: 22,
  },
  categoriesScreenContent: {
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  categoriesTopChrome: {
    gap: theme.spacing.lg,
    width: '100%',
  },
  containedContent: {
    alignSelf: 'center',
    gap: theme.spacing.lg,
    maxWidth: 560,
    paddingHorizontal: theme.spacing.lg,
    width: '100%',
  },
  categoriesHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: theme.spacing.md,
    justifyContent: 'space-between',
  },
  categoriesHeaderTitle: {
    color: theme.colors.text,
    flex: 1,
    fontSize: theme.typography.title2,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 28,
  },
  topVisualBand: {
    gap: theme.spacing.sm,
    paddingHorizontal: theme.spacing.sm,
    width: '100%',
  },
  insightModule: {
    gap: 0,
    paddingHorizontal: 2,
    paddingTop: 0,
  },
  insightBody: {
    height: 202,
  },
  podiumRow: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    gap: 6,
    height: 202,
    justifyContent: 'space-between',
  },
  podiumSlot: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderRadius: theme.radius.large,
    flex: 1,
    gap: 8,
    height: 202,
    justifyContent: 'flex-end',
    minWidth: 0,
    paddingHorizontal: 6,
    paddingTop: theme.spacing.xs,
  },
  podiumSlotFirst: {
    paddingTop: 0,
  },
  podiumSlotDimmed: {
    opacity: 0.36,
  },
  podiumSlotFocused: {
    opacity: 1,
  },
  podiumSlotSelected: {
    opacity: 0.9,
  },
  podiumIconWrap: {
    alignItems: 'center',
    position: 'relative',
  },
  podiumRankMedal: {
    alignItems: 'center',
    borderRadius: theme.radius.pill,
    borderWidth: 1.5,
    height: 25,
    justifyContent: 'center',
    marginBottom: -6,
    minWidth: 25,
    paddingHorizontal: 7,
    zIndex: 2,
  },
  podiumRankMedalFirst: {
    height: 29,
    marginBottom: -7,
    minWidth: 29,
    paddingHorizontal: 8,
  },
  podiumRankMedalEmpty: {
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderStyle: 'dashed',
  },
  podiumRankMedalText: {
    fontSize: theme.typography.caption,
    fontWeight: '900',
    lineHeight: 15,
    textAlign: 'center',
  },
  podiumRankMedalTextFilter: {
    fontSize: 10,
    lineHeight: 12,
  },
  podiumRankMedalTextEmpty: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption,
    fontWeight: '900',
    lineHeight: 15,
    textAlign: 'center',
  },
  podiumIconRing: {
    borderRadius: theme.radius.pill,
    borderWidth: 2,
    padding: 3,
  },
  podiumIconRingFocused: {
    borderWidth: 2.5,
    padding: 4,
  },
  podiumIconRingEmpty: {
    borderColor: theme.colors.border,
    borderStyle: 'dashed',
  },
  podiumCategoryIcon: {
    alignItems: 'center',
    borderRadius: theme.radius.pill,
    height: 50,
    justifyContent: 'center',
    width: 50,
  },
  podiumCategoryIconFirst: {
    height: 62,
    width: 62,
  },
  emptyPodiumIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(248, 250, 252, 0.86)',
    borderRadius: theme.radius.pill,
    height: 50,
    justifyContent: 'center',
    width: 50,
  },
  emptyPodiumIconFirst: {
    height: 62,
    width: 62,
  },
  podiumStep: {
    alignItems: 'center',
    borderRadius: theme.radius.medium,
    borderWidth: 1,
    justifyContent: 'center',
    maxWidth: '100%',
    paddingHorizontal: 8,
    width: '84%',
  },
  podiumStepFocused: {
    borderWidth: 1.5,
  },
  podiumStepFirst: {
    height: 102,
    width: '92%',
  },
  podiumStepSecond: {
    height: 74,
    width: '80%',
  },
  podiumStepThird: {
    height: 54,
    width: '72%',
  },
  podiumStepEmpty: {
    backgroundColor: 'rgba(248, 250, 252, 0.76)',
    borderColor: theme.colors.border,
    borderStyle: 'dashed',
  },
  podiumName: {
    color: theme.colors.text,
    fontSize: theme.typography.caption,
    fontWeight: '800',
    lineHeight: 15,
    maxWidth: '100%',
    textAlign: 'center',
  },
  podiumNameEmpty: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption,
    fontWeight: '800',
    lineHeight: 15,
    maxWidth: '100%',
    textAlign: 'center',
  },
  podiumStepMetric: {
    fontSize: 11,
    fontWeight: '900',
    lineHeight: 15,
    maxWidth: '100%',
    textAlign: 'center',
  },
  filterStack: {
    marginHorizontal: -theme.spacing.sm,
    marginTop: -4,
    overflow: 'visible',
  },
  filterRail: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: 4,
  },
  metricCarouselItem: {
    backgroundColor: 'transparent',
    minHeight: 52,
    position: 'relative',
    width: 104,
  },
  metricCarouselButton: {
    alignItems: 'center',
    borderRadius: theme.radius.medium,
    gap: 4,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: 4,
    paddingVertical: 6,
    width: '100%',
  },
  metricCarouselButtonSelected: {
    backgroundColor: theme.colors.elevated,
    borderColor: theme.colors.hairline,
    borderWidth: 1,
  },
  metricCarouselItemPressed: {
    opacity: 0.76,
  },
  metricCarouselText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption,
    fontWeight: '900',
    lineHeight: 16,
    minWidth: 0,
    textAlign: 'center',
  },
  metricCarouselTextSelected: {
    color: theme.colors.text,
  },
  metricCarouselShadow: {
    backgroundColor: 'rgba(15, 23, 42, 0.18)',
    borderRadius: theme.radius.pill,
    bottom: -1,
    height: 7,
    left: 29,
    opacity: 0.48,
    position: 'absolute',
    right: 29,
  },
  summaryCard: {
    gap: theme.spacing.xs,
  },
  summaryVisualRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  summaryIconCluster: { alignItems: 'center', flexDirection: 'row', minHeight: 42 },
  summaryCategoryOrb: {
    alignItems: 'center',
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    height: 34,
    justifyContent: 'center',
    marginRight: -7,
    width: 34,
  },
  summaryFlowBadge: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.hairline,
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  summaryFlowText: {
    fontSize: theme.typography.caption,
    fontWeight: '800',
    lineHeight: 15,
  },
  summaryEyebrow: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption,
    fontWeight: '800',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  summaryAmount: {
    color: theme.colors.text,
    fontSize: 34,
    fontWeight: '800',
    lineHeight: 40,
  },
  summaryMeta: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.footnote,
    lineHeight: 18,
  },
  activeFilterWrap: { alignItems: 'flex-start' },
  activeFilterPill: {
    alignItems: 'center',
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    flexDirection: 'row',
    gap: theme.spacing.xs,
    maxWidth: '100%',
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: 7,
  },
  activeFilterText: {
    flexShrink: 1,
    fontSize: theme.typography.footnote,
    fontWeight: '800',
    lineHeight: 18,
  },
  searchWrap: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.medium,
    borderWidth: 1,
    flexDirection: 'row',
    gap: theme.spacing.xs,
    minHeight: 52,
    paddingHorizontal: theme.spacing.sm,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 0,
  },
  list: { gap: theme.spacing.sm },
  pressed: { opacity: 0.62 },
  categoryCard: {
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.hairline,
    flexDirection: 'row',
    gap: theme.spacing.sm,
    justifyContent: 'space-between',
  },
  leading: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: theme.spacing.sm,
    minWidth: 0,
  },
  categoryIcon: {
    alignItems: 'center',
    borderRadius: theme.radius.pill,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  categoryCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  categoryTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.callout,
    fontWeight: '800',
    lineHeight: 20,
  },
  categoryMeta: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.footnote,
    lineHeight: 18,
  },
  trailing: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    gap: theme.spacing.xs,
    justifyContent: 'flex-end',
    maxWidth: 148,
  },
  amount: {
    flexShrink: 1,
    fontSize: theme.typography.callout,
    fontWeight: '900',
    lineHeight: 20,
    textAlign: 'right',
  },
  positive: { color: theme.colors.success },
  negative: { color: theme.colors.warning },
  pending: { color: '#ca8a04' },
  cycle: { color: '#2563eb' },
  neutral: { color: theme.colors.text },
});
