import { StyleSheet } from 'react-native';

import { theme } from '@/lib/theme';

const CATEGORY_INSIGHT_BODY_HEIGHT = 202;
const CATEGORY_INSIGHT_PAGER_HEIGHT = CATEGORY_INSIGHT_BODY_HEIGHT + 12;
export const CATEGORY_METRIC_CAROUSEL_ITEM_GAP = 10;
export const CATEGORY_METRIC_CAROUSEL_ITEM_WIDTH = 104;

export const categoriesIndexScreenStyles = StyleSheet.create({
  loadingState: { alignItems: 'center', gap: theme.spacing.sm },
  supportText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.callout,
    lineHeight: 22,
  },
  categoriesScreenContent: {
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  categoriesListContent: {
    flexGrow: 1,
    paddingBottom: theme.spacing.xl,
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  categoriesTopChrome: {
    gap: theme.spacing.lg,
    width: '100%',
  },
  containedContent: {
    alignSelf: 'center',
    gap: theme.spacing.lg,
    maxWidth: 560,
    paddingHorizontal: theme.spacing.lg,
    width: '100%',
  },
  containedListItem: {
    alignSelf: 'center',
    maxWidth: 560,
    paddingHorizontal: theme.spacing.lg,
    width: '100%',
  },
  categoriesControlsSection: {
    marginTop: theme.spacing.lg,
  },
  categoryActivitySectionHeader: {
    paddingTop: theme.spacing.sm,
  },
  categoryActivitySectionTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.title3,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 24,
  },
  categoriesListHeaderGap: {
    height: theme.spacing.lg,
  },
  categoriesListSeparator: {
    height: theme.spacing.sm,
  },
  categoriesListFooter: {
    height: theme.spacing.xl,
  },
  virtualizedCategoriesList: {
    flex: 1,
  },
  categoriesHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: theme.spacing.md,
    justifyContent: 'space-between',
  },
  categoriesHeaderCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  categoriesHeaderTitle: {
    color: theme.colors.text,
    flex: 1,
    fontSize: theme.typography.title2,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 28,
  },
  categoriesHeaderPeriod: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.footnote,
    fontWeight: '700',
    lineHeight: 18,
    minWidth: 0,
  },
  topVisualBand: {
    gap: theme.spacing.sm,
    width: '100%',
  },
  podiumPager: {
    height: CATEGORY_INSIGHT_PAGER_HEIGHT,
    overflow: 'hidden',
    width: '100%',
  },
  syncedPodiumTrack: {
    flexDirection: 'row',
    height: '100%',
  },
  syncedPodiumPage: {
    height: '100%',
  },
  podiumPagerPage: {
    paddingHorizontal: 2,
  },
  insightModule: {
    gap: 0,
    paddingHorizontal: 2,
    paddingTop: 0,
  },
  insightBody: {
    height: CATEGORY_INSIGHT_BODY_HEIGHT,
  },
  podiumRow: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    gap: 6,
    height: CATEGORY_INSIGHT_BODY_HEIGHT,
    justifyContent: 'space-between',
  },
  podiumSlot: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    flex: 1,
    gap: 8,
    height: CATEGORY_INSIGHT_BODY_HEIGHT,
    justifyContent: 'flex-end',
    minWidth: 0,
    outlineColor: 'transparent',
    outlineStyle: 'solid',
    outlineWidth: 0,
    paddingHorizontal: 6,
    paddingTop: theme.spacing.xs,
  },
  podiumSlotFirst: {
    paddingTop: 0,
  },
  podiumSlotDimmed: {
    opacity: 0.38,
    transform: [{ scale: 0.94 }],
  },
  podiumSlotFocused: {
    opacity: 1,
    transform: [{ scale: 1.04 }],
    zIndex: 2,
  },
  podiumSlotSelected: {
    transform: [{ scale: 0.99 }],
  },
  podiumIconWrap: {
    alignItems: 'center',
    overflow: 'visible',
    position: 'relative',
  },
  podiumRankMedal: {
    alignItems: 'center',
    borderRadius: theme.radius.pill,
    borderWidth: 1.5,
    elevation: 2,
    height: 28,
    justifyContent: 'center',
    marginBottom: -6,
    minWidth: 28,
    overflow: 'visible',
    paddingHorizontal: 8,
    position: 'relative',
    zIndex: 2,
  },
  podiumRankMedalFirst: {
    height: 30,
    marginBottom: -7,
    minWidth: 30,
    paddingHorizontal: 9,
  },
  podiumRankMedalEmpty: {
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderStyle: 'dashed',
  },
  podiumRankMedalText: {
    fontSize: theme.typography.caption,
    fontWeight: '900',
    includeFontPadding: false,
    lineHeight: 18,
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  podiumRankMedalTextFilter: {
    fontSize: 10,
    lineHeight: 14,
  },
  podiumRankMedalTextEmpty: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption,
    fontWeight: '900',
    includeFontPadding: false,
    lineHeight: 18,
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  podiumIconRing: {
    borderRadius: theme.radius.pill,
    borderWidth: 2,
    padding: 3,
    zIndex: 1,
  },
  podiumIconRingEmpty: {
    borderColor: theme.colors.border,
    borderStyle: 'dashed',
  },
  podiumCategoryIcon: {
    alignItems: 'center',
    borderRadius: theme.radius.pill,
    height: 50,
    justifyContent: 'center',
    width: 50,
  },
  podiumCategoryIconFirst: {
    height: 62,
    width: 62,
  },
  emptyPodiumIcon: {
    alignItems: 'center',
    backgroundColor: theme.colors.floatingSurface,
    borderRadius: theme.radius.pill,
    height: 50,
    justifyContent: 'center',
    width: 50,
  },
  emptyPodiumIconFirst: {
    height: 62,
    width: 62,
  },
  podiumStep: {
    alignItems: 'center',
    borderRadius: theme.radius.medium,
    borderWidth: 1,
    justifyContent: 'center',
    maxWidth: '100%',
    paddingHorizontal: 8,
    width: '84%',
  },
  podiumStepFirst: {
    height: 94,
    width: '92%',
  },
  podiumStepSecond: {
    height: 74,
    width: '80%',
  },
  podiumStepThird: {
    height: 54,
    width: '72%',
  },
  podiumStepEmpty: {
    backgroundColor: theme.colors.inputGlass,
    borderColor: theme.colors.border,
    borderStyle: 'dashed',
  },
  podiumName: {
    color: theme.colors.text,
    fontSize: theme.typography.caption,
    fontWeight: '800',
    lineHeight: 15,
    maxWidth: '100%',
    textAlign: 'center',
  },
  podiumNameEmpty: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption,
    fontWeight: '800',
    lineHeight: 15,
    maxWidth: '100%',
    textAlign: 'center',
  },
  podiumStepMetric: {
    fontSize: 11,
    fontWeight: '900',
    lineHeight: 15,
    maxWidth: '100%',
    textAlign: 'center',
  },
  filterStack: {
    marginTop: -4,
    overflow: 'visible',
  },
  filterViewport: {
    overflow: 'hidden',
  },
  filterRail: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: CATEGORY_METRIC_CAROUSEL_ITEM_GAP,
    paddingVertical: 4,
  },
  metricCarouselItem: {
    backgroundColor: 'transparent',
    minHeight: 52,
    position: 'relative',
    width: CATEGORY_METRIC_CAROUSEL_ITEM_WIDTH,
  },
  metricCarouselButton: {
    alignItems: 'center',
    borderRadius: theme.radius.medium,
    gap: 4,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: 4,
    paddingVertical: 6,
    width: '100%',
  },
  metricCarouselItemPressed: {
    opacity: 0.76,
  },
  metricCarouselText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption,
    fontWeight: '900',
    lineHeight: 16,
    minWidth: 0,
    textAlign: 'center',
  },
  metricCarouselShadow: {
    backgroundColor: theme.colors.pressedOverlay,
    borderRadius: theme.radius.pill,
    bottom: -1,
    height: 7,
    left: 29,
    opacity: 0.48,
    position: 'absolute',
    right: 29,
  },
  summaryCard: {
    gap: theme.spacing.xs,
  },
  summaryVisualRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  summaryIconCluster: { alignItems: 'center', flexDirection: 'row', minHeight: 42 },
  summaryCategoryOrb: {
    alignItems: 'center',
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    height: 34,
    justifyContent: 'center',
    marginRight: -7,
    width: 34,
  },
  summaryFlowBadge: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.hairline,
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  summaryFlowText: {
    fontSize: theme.typography.caption,
    fontWeight: '800',
    lineHeight: 15,
  },
  summaryEyebrow: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption,
    fontWeight: '800',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  summaryAmount: {
    color: theme.colors.text,
    fontSize: 34,
    fontWeight: '800',
    lineHeight: 40,
  },
  summaryMeta: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.footnote,
    lineHeight: 18,
  },
  searchWrap: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.medium,
    borderWidth: 1,
    flexDirection: 'row',
    gap: theme.spacing.xs,
    minHeight: 52,
    paddingHorizontal: theme.spacing.sm,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 0,
  },
  list: { gap: theme.spacing.sm },
  pressed: { opacity: 0.62 },
  categoryCard: {
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.hairline,
    flexDirection: 'row',
    gap: theme.spacing.sm,
    justifyContent: 'space-between',
  },
  leading: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: theme.spacing.sm,
    minWidth: 0,
  },
  categoryIcon: {
    alignItems: 'center',
    borderRadius: theme.radius.pill,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  categoryCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  categoryTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.callout,
    fontWeight: '800',
    lineHeight: 20,
  },
  categoryMeta: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.footnote,
    lineHeight: 18,
  },
  trailing: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    gap: theme.spacing.xs,
    justifyContent: 'flex-end',
    maxWidth: 148,
  },
  amount: {
    flexShrink: 1,
    fontSize: theme.typography.callout,
    fontWeight: '900',
    lineHeight: 20,
    textAlign: 'right',
  },
  positive: { color: theme.colors.success },
  negative: { color: theme.colors.warning },
  pending: { color: theme.colors.pending },
  danger: { color: theme.colors.danger },
  cycle: { color: theme.colors.cycle },
  neutral: { color: theme.colors.text },
});
