import { StyleSheet } from 'react-native';

import { theme } from '@/lib/theme';

export const settlementDetailScreenStyles = StyleSheet.create({
  supportText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.callout,
    lineHeight: 22,
  },
  detailStory: {
    gap: theme.spacing.xl,
    paddingBottom: theme.spacing.lg,
    paddingHorizontal: theme.spacing.sm,
    paddingTop: theme.spacing.md,
  },
  statusStory: {
    borderBottomColor: theme.colors.hairline,
    borderBottomWidth: StyleSheet.hairlineWidth,
    gap: theme.spacing.sm,
    paddingBottom: theme.spacing.lg,
  },
  statusStoryTop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: theme.spacing.sm,
    justifyContent: 'space-between',
    minHeight: 34,
  },
  statusEyebrow: {
    color: theme.colors.cycle,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 14,
    textTransform: 'uppercase',
  },
  statusHeadline: {
    color: theme.colors.text,
    fontSize: theme.typography.title2,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 28,
  },
  statusBody: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.callout,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 22,
  },
  rewardClaimPanel: {
    borderRadius: theme.radius.large,
    borderWidth: 1,
    gap: theme.spacing.md,
    padding: theme.spacing.md,
  },
  rewardClaimCopy: {
    gap: theme.spacing.xs,
  },
  rewardClaimHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  rewardClaimEyebrow: {
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 14,
    textTransform: 'uppercase',
  },
  rewardClaimTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.callout,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 20,
  },
  rewardClaimBody: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.footnote,
    fontWeight: '700',
    lineHeight: 18,
  },
  detailStoryHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: theme.spacing.sm,
    justifyContent: 'space-between',
    minHeight: 46,
    width: '100%',
  },
  detailCardTitleBlock: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  detailCardTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.title3,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 24,
  },
  detailCardMeta: {
    color: theme.colors.success,
    fontSize: theme.typography.footnote,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 18,
  },
  detailCardHeaderActions: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 1,
    gap: theme.spacing.xs,
    justifyContent: 'flex-end',
    minWidth: 0,
  },
  storyCopyBlock: {
    gap: 6,
  },
  storyEyebrow: {
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 14,
    textTransform: 'uppercase',
  },
  storyBody: {
    color: theme.colors.text,
    fontSize: theme.typography.callout,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 21,
  },
  storySection: {
    gap: theme.spacing.md,
  },
  storySectionHeader: {
    gap: 5,
  },
  storySectionTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.title3,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 24,
  },
  storySectionBody: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.footnote,
    fontWeight: '700',
    lineHeight: 18,
  },
  approvalPillsBlock: {
    alignItems: 'flex-start',
    gap: theme.spacing.md,
    width: '100%',
  },
  detailCardState: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.footnote,
    lineHeight: 18,
  },
  cardActions: {
    alignItems: 'stretch',
    flexDirection: 'row',
    gap: theme.spacing.sm,
    justifyContent: 'center',
  },
  actionStory: {
    gap: theme.spacing.sm,
  },
  actionHint: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.footnote,
    fontWeight: '700',
    lineHeight: 18,
  },
  circleActionButton: {
    alignItems: 'center',
    borderRadius: theme.radius.pill,
    flex: 1,
    flexDirection: 'row',
    gap: 6,
    height: 46,
    justifyContent: 'center',
    paddingHorizontal: theme.spacing.md,
  },
  circleActionLabel: {
    fontSize: theme.typography.footnote,
    fontWeight: '900',
    lineHeight: 18,
  },
  circleActionButtonPressed: {
    opacity: 0.86,
    transform: [{ scale: 0.97 }],
  },
  circleActionButtonDisabled: {
    opacity: 0.55,
  },
  versionsSection: {
    gap: theme.spacing.md,
    paddingBottom: theme.spacing.lg,
    paddingHorizontal: theme.spacing.sm,
    paddingTop: theme.spacing.xs,
  },
  versionsHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: theme.spacing.sm,
    justifyContent: 'space-between',
    minHeight: 38,
  },
  versionsTitleBlock: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  versionsTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.callout,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 20,
  },
  versionsSubtitle: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption,
    fontWeight: '700',
    lineHeight: 16,
  },
  versionsCountBadge: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceSoft,
    borderColor: theme.colors.hairline,
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    height: 30,
    justifyContent: 'center',
    minWidth: 30,
    paddingHorizontal: theme.spacing.xs,
  },
  versionsCountText: {
    color: theme.colors.text,
    fontSize: theme.typography.footnote,
    fontWeight: '900',
    lineHeight: 18,
  },
  versionStoryPanel: {
    paddingHorizontal: 0,
  },
  replacementAction: {
    marginTop: theme.spacing.xs,
  },
});
